[package]
name = "trunk-util"
version = "0.1.0"
edition = "2021"

[dependencies]
tokio = { version = "1", default-features = false, features = ["fs"] }
thiserror = "1"
flate2 = "1"
tar = "0.4"
zip = "0.6"
derive_more = "0.99.17"
